"""Full workbench regression. Test an actual React build with GLASS_REACT_DIR or dist.
The current sandbox uses an offline TS/React 19.1.1 harness; see TESTING.md.
"""
import asyncio, io, json, os, mimetypes, shutil
from pathlib import Path
from urllib.parse import urlsplit, unquote
from PIL import Image, ImageChops, ImageStat
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]
REACT=Path(os.environ.get('GLASS_REACT_DIR',ROOT/'dist')).resolve()
STATIC=(ROOT/'dist-static').resolve()
OUT=ROOT/'tests/workbench-artifacts';OUT.mkdir(exist_ok=True)
ORIGIN='https://glass-test.invalid'
results=[]
def check(name,ok,detail=None):
 results.append({'test':name,'passed':bool(ok),'detail':detail})
 print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 if not ok: raise AssertionError(name+': '+str(detail))
def delta(a,b):
 return sum(ImageStat.Stat(ImageChops.difference(Image.open(io.BytesIO(a)).convert('RGB'),Image.open(io.BytesIO(b)).convert('RGB'))).mean)/3
async def load(page,root,prefix='/'):
 requests=[];missing=[]
 async def serve(route):
  requests.append(route.request.url);path=unquote(urlsplit(route.request.url).path)
  f=(root/(path[len(prefix):] or 'index.html')).resolve()
  if not path.startswith(prefix) or not f.is_relative_to(root) or not f.is_file():
   missing.append(route.request.url);await route.fulfill(status=404,body='not found');return
  await route.fulfill(content_type=mimetypes.guess_type(str(f))[0] or 'application/octet-stream',body=f.read_bytes(),headers={'Access-Control-Allow-Origin':'*','Accept-Ranges':'bytes'})
 await page.route(ORIGIN+'/**',serve)
 html=(root/'index.html').read_text().replace('<head>','<head><base href="'+ORIGIN+prefix+'">')
 await page.set_content(html,wait_until='load')
 await page.locator('#main-glass[data-glass-renderer]').wait_for()
 await page.wait_for_timeout(500)
 return requests,missing
async def wait(page,n=170): await page.wait_for_timeout(n)
async def set_input(page,id,value):
 await page.locator('#'+id).evaluate('''(el,v)=>{const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(el,String(v));el.dispatchEvent(new Event('input',{bubbles:true}));}''',value)
 await wait(page)
async def main():
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path=os.environ.get('CHROMIUM_BIN') or shutil.which('chromium'),args=['--no-sandbox'])
  page=await browser.new_page(viewport={'width':1440,'height':1140},device_scale_factor=1)
  errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  req,missing=await load(page,REACT)
  check('React default is full workbench',await page.locator('[data-application="full-workbench"]').count()==1 and await page.locator('.react-demo').count()==0)
  check('Inspector is present and visible',await page.locator('.inspector').is_visible())
  boxes=await page.evaluate('Object.fromEntries([".viewport",".inspector"].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return [s,{x:r.x,y:r.y,w:r.width}]}))')
  check('Inspector is on the right at desktop',boxes['.inspector']['x']>boxes['.viewport']['x']+boxes['.viewport']['w'] and abs(boxes['.inspector']['y']-boxes['.viewport']['y'])<1)
  check('Four optical parameters exposed',await page.locator('.inspector input[type=range]').count()==4)
  await page.locator('[data-backdrop-choice=wallpaper]').click();await wait(page,700)
  check('Default actual wallpaper decoded',await page.locator('#media-image').evaluate('(i)=>i.complete&&i.naturalWidth===1920'))
  check('Eleven mounted material instances',await page.locator('[data-lg-defs]').count()==11)
  check('SVG material active',await page.locator('#main-glass').get_attribute('data-glass-renderer')=='svg')
  await page.screenshot(path=str(OUT/'react-desktop.png'),full_page=True)
  old=await page.locator('#main-glass').bounding_box()
  await page.mouse.move(old['x']+120,old['y']+75);await page.mouse.down();await page.mouse.move(old['x']+45,old['y']+112,steps=6)
  check('Dragging state changes', 'dragging' in await page.locator('#main-glass').get_attribute('class'))
  await page.mouse.up();await wait(page)
  new=await page.locator('#main-glass').bounding_box()
  check('Pointer drag changes card position',abs(new['x']-old['x']+75)<2 and abs(new['y']-old['y']-37)<2,[old,new])
  check('Pointer drag has no blue focus ring',await page.locator('#main-glass').evaluate('(e)=>getComputedStyle(e).outlineStyle')=='none')
  await page.locator('#main-glass').press('ArrowRight');await wait(page)
  after=await page.locator('#main-glass').bounding_box()
  check('Keyboard ArrowRight moves 10px',abs(after['x']-new['x']-10)<1)
  await page.locator('#main-glass').press('Shift+ArrowDown');await wait(page)
  after2=await page.locator('#main-glass').bounding_box()
  check('Shift ArrowDown moves 30px',abs(after2['y']-after['y']-30)<1)
  check('Keyboard keeps card ring removed',await page.locator('#main-glass').evaluate('(e)=>getComputedStyle(e).outlineStyle')=='none')
  await page.locator('#main-glass').press('Home');await wait(page)
  home=await page.locator('#main-glass').bounding_box()
  check('Home restores default card position',abs(home['x']-old['x'])<1 and abs(home['y']-old['y'])<1)
  for k,value,output in [('refraction',72,'72'),('bevel',15,'15 px'),('blur',2.5,'2.50 px'),('dispersion',2.6,'2.60')]:
   await set_input(page,k,value)
   check('React parameter updates '+k,await page.locator('#'+k+'-output').inner_text()==output)
  check('Refraction updates actual filter',await page.locator('[data-lg-defs] feDisplacementMap').nth(1).get_attribute('scale')=='72')
  check('Blur updates actual filter',await page.locator('[data-lg-defs] feGaussianBlur').first.get_attribute('stdDeviation')=='2.5')
  for shape in ['circle','pill','card']:
   await page.locator('[data-shape-choice='+shape+']').click();await wait(page)
   check('Shape switch '+shape,await page.locator('#main-glass').get_attribute('data-shape')==shape)
  await page.locator('#show-content').uncheck()
  check('Foreground text toggle',not await page.locator('#main-glass .lg-content').is_visible())
  await page.locator('[data-mode=css]').click();await wait(page)
  check('CSS mode reaches every material',await page.locator('[data-glass-renderer=css]').count()==11)
  await page.locator('[data-mode=auto]').click();await wait(page)
  check('SVG mode restored',await page.locator('[data-glass-renderer=svg]').count()==11)
  await page.locator('#reset').click();await wait(page)
  check('Reset restores all parameters',await page.locator('#refraction').input_value()=='56' and await page.locator('#bevel').input_value()=='22' and await page.locator('#blur').input_value()=='0.35' and await page.locator('#dispersion').input_value()=='1.2')
  await page.locator('[data-backdrop-choice=wallpaper]').click();await wait(page,500)
  for id in ['wufeng','huayu','yunxi']:
   await page.locator('[data-media-id='+id+']').click();await wait(page)
   check('Wallpaper '+id,await page.locator('#media-image').evaluate('(i)=>i.complete&&i.naturalWidth>0') and id in await page.locator('#media-image').get_attribute('src'))
  await page.locator('[data-backdrop-choice=grid]').click();await page.locator('#show-content').uncheck();await wait(page)
  before=await page.locator('#main-glass').screenshot();await set_input(page,'refraction',0);after=await page.locator('#main-glass').screenshot()
  check('Parameter actually changes refracted pixels',delta(before,after)>.3,delta(before,after))
  await page.locator('[data-backdrop-choice=text]').click()
  check('Text background visible',await page.locator('.text-sheet').is_visible())
  await page.locator('[data-backdrop-choice=spectrum]').click();await wait(page)
  before=await page.locator('#main-glass').screenshot();await page.locator('#change-color').click();await wait(page);after=await page.locator('#main-glass').screenshot()
  check('Spectrum palette changes visible background',delta(before,after)>2,delta(before,after))
  await page.locator('#reset').click();await page.locator('[data-backdrop-choice=video]').click();await wait(page,850)
  state=await page.locator('#media-video').evaluate('(v)=>({w:v.videoWidth,time:v.currentTime,paused:v.paused,muted:v.muted,loop:v.loop})')
  check('Real video plays behind card',state['w']==960 and state['time']>0 and not state['paused'],state)
  check('Video is muted looping',state['muted'] and state['loop'])
  await page.locator('#media-play').click();await wait(page);t=await page.locator('#media-video').evaluate('(v)=>v.currentTime');await wait(page,250)
  check('Pause button stops video time',abs(t-await page.locator('#media-video').evaluate('(v)=>v.currentTime'))<.05)
  await page.locator('#media-play').click();await wait(page,250)
  check('Resume button resumes video',not await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.locator('[data-media-id=cloud-motion]').click();await wait(page,550)
  check('Second video loads',await page.locator('#media-video').evaluate('(v)=>v.videoWidth===960&&v.currentTime>0&&!v.paused'))
  await page.locator('[data-backdrop-choice=wallpaper]').click();await wait(page)
  check('Leaving video pauses it',await page.locator('#media-video').evaluate('(v)=>v.paused&&v.hidden'))
  await page.emulate_media(reduced_motion='reduce');await page.locator('[data-backdrop-choice=video]').click();await wait(page,350)
  check('Reduced motion prevents autoplay',await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.locator('#media-play').click();await wait(page,350)
  check('Explicit video play under reduced motion',not await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.emulate_media(reduced_motion='no-preference')
  await page.locator('#media-file').set_input_files(str(ROOT/'public/assets/wallpapers/wufeng.webp'));await wait(page,600)
  check('Local image import preserved',await page.locator('#media-image').evaluate('(i)=>i.src.startsWith("blob:")&&i.naturalWidth===1920'))
  await page.locator('#media-file').set_input_files(str(ROOT/'public/assets/videos/pearl-motion.mp4'));await wait(page,800)
  check('Local video import preserved',await page.locator('#media-video').evaluate('(v)=>v.src.startsWith("blob:")&&v.videoWidth===960&&!v.paused'))
  await page.locator('#media-file').set_input_files({'name':'broken.mp4','mimeType':'video/mp4','buffer':b'not a valid video'});await wait(page,350)
  check('Corrupt import keeps previous background','原背景已保留' in await page.locator('#media-toast').inner_text() and await page.locator('#media-video').evaluate('(v)=>v.videoWidth===960'))
  await page.locator('#reset').click();await wait(page)
  check('Six compact controls preserved',await page.locator('.sample').count()==6)
  check('Button decorative line remains removed',await page.locator('.sample-button .sample-body').evaluate('(e)=>getComputedStyle(e,"::before").content')=='none')
  await page.locator('#demo-button').click();await page.locator('#demo-button').press('Enter')
  check('Button state updates with click and key',await page.locator('#click-output').inner_text()=='DONE · 2')
  await page.locator('#cancel-button').click();check('Cancel resets state',await page.locator('#click-output').inner_text()=='READY')
  await page.locator('#favorite-button').click();check('Favorite toggles',await page.locator('#favorite-button').get_attribute('aria-pressed')=='true')
  await page.locator('#demo-switch').click();await page.locator('#focus-switch').press('Space')
  check('Switches remain independent',await page.locator('#switch-output').inner_text()=='OFF / ON')
  await page.locator('#demo-slider').press('End');check('Slider reaches maximum',await page.locator('#slider-output').inner_text()=='100%')
  await page.locator('#demo-slider').press('Home');check('Slider reaches minimum',await page.locator('#slider-output').inner_text()=='0%')
  await page.get_by_role('radio',name='最近',exact=True).focus();await page.keyboard.press('ArrowRight')
  check('Segmented arrow navigation',await page.get_by_role('radio',name='收藏',exact=True).get_attribute('aria-checked')=='true')
  await page.locator('[data-chip="开发"]').click();check('Chips multi-select',await page.locator('#chip-output').inner_text()=='2 SELECTED')
  await page.locator('[data-tool=pen]').click();check('Toolbar selection',await page.locator('#tool-output').inner_text()=='绘制')
  await page.keyboard.press('ArrowRight');check('Toolbar arrow focus',await page.evaluate('document.activeElement.dataset.tool')=='crop')
  await page.locator('#undo-tool').click();check('Toolbar reset',await page.locator('#tool-output').inner_text()=='选择')
  await page.locator('#sample-tone').click();check('Sample background tone toggle',await page.locator('#samples').get_attribute('data-tone')=='dark')
  await page.locator('#reset').click();await wait(page)
  check('No extra filter instances after updates',await page.locator('[data-lg-defs]').count()==11)
  # Compare real CSS geometry against the same complete static page, not a mock.
  static=await browser.new_page(viewport={'width':1440,'height':1140});sr,sm=await load(static,STATIC)
  async def geometry(p):
   return await p.evaluate('''Object.fromEntries(['.workspace','.viewport','.stage','.inspector','.samples-grid','#main-glass'].map(s=>{const r=document.querySelector(s).getBoundingClientRect();return [s,{x:r.x,y:r.y,width:r.width,height:r.height}]}))''')
  parity={}
  for width in [320,390,768,1024,1440]:
   await page.set_viewport_size({'width':width,'height':1140});await static.set_viewport_size({'width':width,'height':1140});await wait(page,350)
   g1,g2=await geometry(page),await geometry(static);parity[width]={'react':g1,'static':g2}
   largest=max(abs(g1[s][k]-g2[s][k]) for s in g1 for k in g1[s])
   check(f'Layout matches full static workbench {width}px',largest<1.1,largest)
   check(f'No horizontal overflow {width}px',await page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
   if width==390:await page.screenshot(path=str(OUT/'react-mobile.png'),full_page=True)
  await page.locator('#main-glass').press('Home');await wait(page)
  await page.screenshot(path=str(OUT/'react-desktop-final.png'),full_page=True)
  await static.screenshot(path=str(OUT/'static-desktop.png'),full_page=True)
  await page.emulate_media(forced_colors='active');await wait(page)
  check('Forced-colors fallback preserved',await page.locator('#main-glass').get_attribute('data-glass-renderer')=='solid')
  await page.emulate_media(forced_colors='none');await wait(page)
  sub=await browser.new_page(viewport={'width':1440,'height':1140});subErrors=[];sub.on('pageerror',lambda e:subErrors.append(str(e)))
  pr,pm=await load(sub,REACT,'/lab/glass/');await wait(sub)
  await sub.locator('[data-backdrop-choice=wallpaper]').click();await wait(sub,700)
  check('React subdirectory image loads',await sub.locator('#media-image').evaluate('(i)=>i.complete&&i.naturalWidth===1920'))
  await sub.locator('[data-backdrop-choice=video]').click();await wait(sub,600)
  check('React subdirectory video loads',await sub.locator('#media-video').evaluate('(v)=>v.videoWidth===960&&v.currentTime>0'))
  check('No relative path resource failures',not missing and not sm and not pm,missing+sm+pm)
  check('No browser application exceptions',not errors and not subErrors,errors+subErrors)
  (OUT/'layout-parity.json').write_text(json.dumps(parity,indent=2))
  (ROOT/'tests/workbench-results.json').write_text(json.dumps({'reactInput':str(REACT),'browser':browser.version,'runtime':'React 19.1.1 production (offline test harness, not Vite build)' if 'harness' in str(REACT) else 'normal React build','passed':sum(r['passed'] for r in results),'tests':results,'pageErrors':errors,'missingResources':missing+pm+sm},ensure_ascii=False,indent=2))
  await browser.close()
if __name__=='__main__':
 if not (REACT/'index.html').is_file():raise SystemExit('Run npm run build first, or point GLASS_REACT_DIR at the built React site.')
 asyncio.run(main())
