"""Offline asset-route Chromium checks for the light static site and compact controls.
No live HTTP navigation or Cloudflare deployment; requests are fulfilled from dist.
This does not test React runtime or Safari/Firefox; see TESTING.md.
"""
import asyncio, io, json, os, shutil, mimetypes
from urllib.parse import urlsplit, unquote
from pathlib import Path
from PIL import Image, ImageChops, ImageStat
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'tests/static-artifacts';OUT.mkdir(exist_ok=True)
DIST=ROOT/'dist-static'
ORIGIN='https://glass-test.invalid'
asset_requests=[]
asset_missing=[]
async def load_site(page,prefix='/'):
    async def serve(route):
        u=route.request.url;path=unquote(urlsplit(u).path);asset_requests.append(u)
        if not path.startswith(prefix):
            asset_missing.append(u);await route.fulfill(status=404,body='outside mount');return
        name=path[len(prefix):] or 'index.html';f=(DIST/name).resolve()
        if not f.is_relative_to(DIST) or not f.is_file():
            asset_missing.append(u);await route.fulfill(status=404,body='not found');return
        data=f.read_bytes();mime=mimetypes.guess_type(str(f))[0] or 'application/octet-stream'
        await route.fulfill(status=200,content_type=mime,body=data,headers={'Accept-Ranges':'bytes'})
    await page.route(ORIGIN+'/**',serve)
    # Only test harness has a base tag. Production index.html has no base tag.
    html=(DIST/'index.html').read_text().replace('<head>','<head><base href="'+ORIGIN+prefix+'">')
    await page.set_content(html,wait_until='load')

results=[]
def check(name,ok,detail=None):
    results.append({'test':name,'passed':bool(ok),'detail':detail})
    print(('PASS ' if ok else 'FAIL ')+name,flush=True)
    if not ok:raise AssertionError(name+': '+str(detail))
def delta(a,b):
    a=Image.open(io.BytesIO(a)).convert('RGB');b=Image.open(io.BytesIO(b)).convert('RGB')
    return sum(ImageStat.Stat(ImageChops.difference(a,b)).mean)/3
async def wait(page,n=220):await page.wait_for_timeout(n)
async def set_input(page,id,v):
    await page.locator('#'+id).evaluate('(el,v)=>{el.value=String(v);el.dispatchEvent(new Event("input",{bubbles:true}));}',v);await wait(page)
async def main():
 async with async_playwright() as p:
  browser=await p.chromium.launch(executable_path=os.environ.get('CHROMIUM_BIN') or shutil.which('chromium'),args=['--no-sandbox'])
  errors=[];requests=[]
  page=await browser.new_page(viewport={'width':1440,'height':1140},device_scale_factor=1)
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('request',lambda r:requests.append(r.url))
  await load_site(page);await wait(page,850)
  await page.locator('[data-backdrop-choice=wallpaper]').click();await wait(page,700)
  check('Default wallpaper actually decodes',await page.locator('#media-image').evaluate('(i)=>i.complete&&i.naturalWidth===1920'))
  check('Main refraction uses SVG',await page.locator('#main-glass').get_attribute('data-glass-renderer')=='svg')
  count=await page.locator('[data-lg-defs]').count()
  check('11 unique material instances',count==11 and await page.evaluate('new Set([...document.querySelectorAll("[data-lg-defs] filter")].map(x=>x.id)).size')==count,count)
  check('Video stays dormant until selected',await page.locator('#media-video').evaluate('(v)=>v.paused&&!v.getAttribute("src")'))
  check('3 wallpaper thumbnails',await page.locator('.media-thumb').count()==3)
  await page.screenshot(path=str(OUT/'desktop.png'),full_page=True)
  before=await page.locator('#main-glass').screenshot()
  map_before=await page.locator('[data-lg-defs] feImage').first.get_attribute('href')
  for id in ['wufeng','huayu','yunxi']:
    await page.locator(f'[data-media-id="{id}"]').click();await wait(page,240)
    check('Wallpaper selection '+id,await page.evaluate('glassDemo.activeMedia.id')==id and await page.locator('#media-image').evaluate('(i)=>i.complete&&i.naturalWidth>0'))
  await page.locator('[data-media-id=wufeng]').click();await wait(page,300)
  after=await page.locator('#main-glass').screenshot()
  check('Wallpaper pixels change through the lens',delta(before,after)>5,delta(before,after))
  check('Media changes reuse displacement texture',map_before==await page.locator('[data-lg-defs] feImage').first.get_attribute('href'))
  await page.screenshot(path=str(OUT/'wufeng.png'),full_page=True)
  check('6 compact control families',await page.locator('.sample').count()==6)
  check('Removed artificial line behind button',await page.locator('.sample-button .sample-body').evaluate('(x)=>getComputedStyle(x,"::before").content')=='none')
  check('Button is 36px high',round((await page.locator('#demo-button').bounding_box())['height'])==36)
  check('Switch track is 44 x 26',await page.locator('#demo-switch .lg-switch-track').evaluate('(x)=>[x.offsetWidth,x.offsetHeight]')==[44,26])
  check('Switch keeps a 44px hit target',await page.locator('#demo-switch').evaluate('(x)=>x.offsetHeight')==44)
  check('Slider knob is 22 x 22',await page.locator('.lg-range-thumb').evaluate('(x)=>[x.offsetWidth,x.offsetHeight]')==[22,22])
  await page.locator('#demo-button').click();await page.locator('#demo-button').press('Enter')
  check('Button mouse and keyboard',await page.locator('#click-output').inner_text()=='DONE · 2')
  await page.locator('#cancel-button').click()
  check('Cancel resets example action',await page.locator('#click-output').inner_text()=='READY')
  await page.locator('#favorite-button').click()
  check('Icon button toggles favorite',await page.locator('#favorite-button').get_attribute('aria-pressed')=='true')
  await page.locator('#demo-switch').click();await page.locator('#focus-switch').press('Space')
  check('Both switches have independent state',await page.locator('#switch-output').inner_text()=='OFF / ON')
  await page.locator('#demo-switch').press('Space')
  check('Switch keyboard toggles back',await page.locator('#demo-switch').get_attribute('aria-checked')=='true')
  await page.locator('#demo-slider').press('End');await wait(page)
  check('Slider maximum',await page.locator('#slider-output').inner_text()=='100%')
  parent=await page.locator('#demo-range').bounding_box();thumb=await page.locator('.lg-range-thumb').bounding_box()
  check('Slider thumb aligns with max endpoint',abs(parent['x']+parent['width']-thumb['x']-thumb['width'])<1)
  await page.locator('#demo-slider').press('Home');await wait(page)
  thumb=await page.locator('.lg-range-thumb').bounding_box()
  check('Slider minimum and position',await page.locator('#slider-output').inner_text()=='0%' and abs(parent['x']-thumb['x'])<1)
  await page.locator('#demo-slider').press('ArrowRight')
  check('Slider ArrowRight increment',await page.locator('#demo-slider').input_value()=='1')
  await page.locator('[data-segment=recent]').focus();await page.keyboard.press('ArrowRight')
  check('Segmented arrow selection',await page.locator('[data-segment=saved]').get_attribute('aria-checked')=='true')
  await page.keyboard.press('End')
  check('Segmented End key',await page.locator('[data-segment=all]').get_attribute('aria-checked')=='true')
  check('Segmented has exactly one tab stop',await page.locator('[data-segment][tabindex="0"]').count()==1)
  await page.locator('[data-chip="开发"]').click()
  check('Chip multi-selection',await page.locator('#chip-output').inner_text()=='2 SELECTED')
  await page.locator('[data-chip="设计"]').press('Space')
  check('Chip deselection via keyboard',await page.locator('#chip-output').inner_text()=='1 SELECTED')
  await page.locator('[data-tool=pen]').click()
  check('Toolbar choice',await page.locator('#tool-output').inner_text()=='绘制')
  await page.keyboard.press('ArrowRight')
  check('Toolbar roving focus',await page.evaluate('document.activeElement.dataset.tool')=='crop')
  await page.locator('#undo-tool').click()
  check('Toolbar reset works',await page.locator('#tool-output').inner_text()=='选择')
  await page.locator('#sample-tone').click();await wait(page)
  check('Sample dark surface toggle',await page.locator('#samples').get_attribute('data-tone')=='dark')
  await page.screenshot(path=str(OUT/'dark-controls.png'),full_page=True)
  await page.locator('#reset').click();await wait(page)
  check('Reset restores controls and background',await page.locator('#demo-slider').input_value()=='48' and await page.locator('#samples').get_attribute('data-tone')=='light' and await page.locator('#stage').get_attribute('data-backdrop')=='spectrum')
  for shape in ['circle','pill','card']:
    await page.locator('[data-shape-choice='+shape+']').click();await wait(page)
    check('Shape selection '+shape,await page.locator('#main-glass').get_attribute('data-shape')==shape)
  box=await page.locator('#main-glass').bounding_box()
  await page.mouse.move(box['x']+100,box['y']+70);await page.mouse.down();await page.mouse.move(box['x']+50,box['y']+100,steps=5);await page.mouse.up();await wait(page)
  box2=await page.locator('#main-glass').bounding_box()
  check('Card really moves',abs(box2['x']-box['x'])>30)
  check('No ring during pointer focus',await page.locator('#main-glass').evaluate('(x)=>getComputedStyle(x).outlineStyle')=='none')
  await page.locator('#main-glass').press('ArrowLeft')
  check('Keyboard move keeps ring removed',await page.locator('#main-glass').evaluate('(x)=>getComputedStyle(x).outlineStyle')=='none')
  await page.locator('#main-glass').press('Home')
  await page.locator('[data-backdrop-choice=grid]').click();await page.locator('#show-content').uncheck();await wait(page)
  g=await page.locator('#main-glass').screenshot();await set_input(page,'refraction',0);flat=await page.locator('#main-glass').screenshot()
  check('Grid refraction remains real',delta(g,flat)>.3,delta(g,flat))
  await page.locator('[data-mode=css]').click();await wait(page)
  check('CSS fallback reaches all materials',await page.locator('[data-glass-renderer=css]').count()==11)
  await page.locator('[data-mode=auto]').click();await wait(page)
  check('Restore SVG mode',await page.locator('[data-glass-renderer=svg]').count()==11)
  await page.locator('[data-backdrop-choice=text]').click()
  check('DOM text backdrop preserved',await page.locator('.text-sheet').is_visible())
  await page.locator('[data-backdrop-choice=spectrum]').click();await wait(page)
  a=await page.locator('#main-glass').screenshot();await page.locator('#change-color').click();await wait(page);b=await page.locator('#main-glass').screenshot()
  check('Spectrum palette toggle preserved',delta(a,b)>2)
  await page.locator('#reset').click();await page.locator('[data-backdrop-choice=video]').click();await wait(page,750)
  v=await page.locator('#media-video').evaluate('(v)=>({time:v.currentTime,paused:v.paused,w:v.videoWidth,muted:v.muted,loop:v.loop,inline:v.playsInline,error:v.error?.message})')
  check('Real MP4 video decodes and plays',v['w']==960 and v['time']>0 and not v['paused'],v)
  check('Silent looping inline video',v['muted'] and v['loop'] and v['inline'])
  check('2 video thumbnails',await page.locator('.media-thumb').count()==2)
  await page.locator('#media-play').click();await wait(page)
  t0=await page.locator('#media-video').evaluate('(v)=>v.currentTime');await wait(page,380);t1=await page.locator('#media-video').evaluate('(v)=>v.currentTime')
  check('Video pause is real',abs(t1-t0)<.05)
  await page.locator('#media-video').evaluate('(v)=>v.currentTime=1');await wait(page,300)
  first=await page.locator('#main-glass').screenshot();href=await page.locator('[data-lg-defs] feImage').first.get_attribute('href')
  await page.locator('#media-video').evaluate('(v)=>v.currentTime=4');await wait(page,300)
  second=await page.locator('#main-glass').screenshot()
  check('Video frames refract under glass',delta(first,second)>.8,delta(first,second))
  check('Video needs no JS per-frame texture regeneration',href==await page.locator('[data-lg-defs] feImage').first.get_attribute('href'))
  await page.screenshot(path=str(OUT/'video.png'),full_page=True)
  await page.locator('#media-play').click();await wait(page,250)
  check('Video resume works',not await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.locator('[data-media-id=cloud-motion]').click();await wait(page,500)
  check('Second MP4 video plays',await page.evaluate('glassDemo.activeMedia.id')=='cloud-motion' and await page.locator('#media-video').evaluate('(v)=>v.currentTime>0&&!v.paused'))
  await page.locator('[data-backdrop-choice=wallpaper]').click();await wait(page,240)
  check('Leaving video pauses decoding',await page.locator('#media-video').evaluate('(v)=>v.paused&&v.hidden'))
  await page.emulate_media(reduced_motion='reduce');await page.locator('[data-backdrop-choice=video]').click();await wait(page,320)
  check('Reduced motion does not auto-play',await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.locator('#media-play').click();await wait(page,250)
  check('Reduced motion still allows explicit play',not await page.locator('#media-video').evaluate('(v)=>v.paused'))
  # Visibility is simulated because headless tabs do not expose a visible GUI.
  await page.evaluate('Object.defineProperty(document,"hidden",{configurable:true,get:()=>true});document.dispatchEvent(new Event("visibilitychange"));');await wait(page)
  check('Hidden page pauses video',await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.evaluate('Object.defineProperty(document,"hidden",{configurable:true,get:()=>false});document.dispatchEvent(new Event("visibilitychange"));');await wait(page)
  check('Previously playing video resumes on visibility',not await page.locator('#media-video').evaluate('(v)=>v.paused'))
  await page.emulate_media(reduced_motion='no-preference')
  await page.evaluate('window.revoked=[];const revoke=URL.revokeObjectURL;URL.revokeObjectURL=(u)=>{window.revoked.push(u);revoke.call(URL,u);};')
  await page.locator('#media-file').set_input_files(str(ROOT/'public/assets/wallpapers/wufeng.webp'));await wait(page,600)
  check('Local image import uses blob, no upload',await page.locator('#media-image').evaluate('(i)=>i.src.startsWith("blob:")&&i.naturalWidth===1920'))
  blob=await page.locator('#media-image').get_attribute('src')
  await page.locator('#media-file').set_input_files(str(ROOT/'public/assets/wallpapers/huayu.webp'));await wait(page,500)
  check('Replacing imported image releases prior URL',await page.evaluate('(u)=>window.revoked.includes(u)',blob))
  await page.locator('#media-file').set_input_files(str(ROOT/'public/assets/videos/pearl-motion.mp4'));await wait(page,700)
  check('Local MP4 import really plays',await page.locator('#media-video').evaluate('(v)=>v.src.startsWith("blob:")&&v.videoWidth===960&&!v.paused'))
  await page.locator('#media-file').set_input_files({'name':'broken.mp4','mimeType':'video/mp4','buffer':b'not a video'});await wait(page,500)
  check('Corrupt video reports failure, retains prior scene','原背景已保留' in await page.locator('#media-toast').inner_text() and await page.locator('#media-video').evaluate('(v)=>v.videoWidth===960'))
  await page.locator('#media-file').set_input_files({'name':'note.txt','mimeType':'text/plain','buffer':b'hello'});await wait(page)
  check('Unsupported import gets useful error','请选择' in await page.locator('#media-toast').inner_text())
  await page.locator('#reset').click();await wait(page)
  for width in [320,390,768,1024,1440]:
    await page.set_viewport_size({'width':width,'height':1140});await wait(page,350)
    overflow=await page.evaluate('document.documentElement.scrollWidth>innerWidth')
    check(f'No horizontal overflow {width}px',not overflow)
    rect=await page.locator('#main-glass').bounding_box();parent=await page.locator('#stage').bounding_box()
    check(f'Lens stays inside stage {width}px',rect['x']>=parent['x'] and rect['x']+rect['width']<=parent['x']+parent['width']+1)
    if width==390:
      await page.locator('#media-toast').evaluate('(x)=>x.hidden=true')
      await page.screenshot(path=str(OUT/'mobile.png'),full_page=True)
  await page.locator('#media-toast').evaluate('(x)=>x.hidden=true')
  await page.emulate_media(forced_colors='active');await wait(page)
  check('Forced colors use solid material',await page.locator('#main-glass').get_attribute('data-glass-renderer')=='solid')
  check('Forced colors honor system text color',await page.locator('#main-glass .lg-content').evaluate('''(x)=>{const probe=document.createElement('span');probe.style.color='CanvasText';document.body.append(probe);const expected=getComputedStyle(probe).color;probe.remove();return getComputedStyle(x).color===expected;}'''))
  await page.emulate_media(forced_colors='none');await wait(page)
  check('No third-party network requests',all(not u.startswith(('http:','https:')) or u.startswith(ORIGIN+'/') for u in requests),len(requests))
  check('All local URLs resolve, including CSS background URLs',not asset_missing,asset_missing)
  check('No runtime JS errors',not errors,errors)
  await page.evaluate('glassDemo.dispose()');await wait(page)
  check('Dispose removes all material SVGs',await page.locator('[data-lg-defs]').count()==0)
  check('Dispose pauses and detaches video',await page.locator('#media-video').evaluate('(v)=>v.paused&&!v.getAttribute("src")'))
  check('Imported object URLs released on dispose',await page.evaluate('window.revoked.length>=3'))
  # A separate mount checks nested relative paths, with no root-absolute asset refs.
  nested=await browser.new_page(viewport={'width':1440,'height':1140})
  await load_site(nested,'/lab/glass/');await wait(nested,850)
  await nested.locator('[data-backdrop-choice=wallpaper]').click();await wait(nested,700)
  check('Subdirectory image decodes',await nested.locator('#media-image').evaluate('(i)=>i.complete&&i.naturalWidth===1920'))
  check('Subdirectory image URL follows mount', '/lab/glass/assets/wallpapers/' in await nested.locator('#media-image').evaluate('(i)=>i.currentSrc'))
  check('Subdirectory CSS background follows mount','/lab/glass/assets/wallpapers/' in await nested.locator('.sample').first.evaluate('(e)=>getComputedStyle(e).backgroundImage'))
  await nested.locator('[data-backdrop-choice=video]').click();await wait(nested,700)
  check('Subdirectory MP4 decodes',await nested.locator('#media-video').evaluate('(v)=>v.videoWidth===960&&v.currentTime>0'))
  check('Subdirectory MP4 URL follows mount','/lab/glass/assets/videos/' in await nested.locator('#media-video').evaluate('(v)=>v.currentSrc'))
  check('Nested mount has no missing media',not asset_missing,asset_missing)
  await nested.close()
  return browser.version
try:
 version=asyncio.run(main())
finally:
 (ROOT/'tests/static-results.json').write_text(json.dumps({'browser':locals().get('version','Chromium'),'checks':results,'passed':sum(x['passed'] for x in results),'total':len(results)},ensure_ascii=False,indent=2))
